/**
 * @fileoverview Stream processor to isolate and sanitize Mermaid diagrams from CLI output.
 *
 * This script acts as a pipe filter between graph generation tools (e.g., `typescript-graph`)
 * and the Mermaid CLI (`mmdc`). It reads from `stdin` and writes to `stdout`, performing
 * three critical operations on the fly:
 *
 * 1. Isolation: Scans the standard input stream to locate the start of the Mermaid diagram,
 * silently dropping any preceding console logs or noise generated by the upstream tool.
 *
 * 2. Configuration: Prepend a base Mermaid configuration block (disabling HTML labels)
 * to ensure the resulting SVG/PDF is strictly compatible with standard desktop viewers
 * (such as the Gnome Image Viewer) that fail to render embedded HTML.
 *
 * 3. Path Sanitization: Strips machine-specific absolute paths (CWD) from the generated
 * diagram nodes, accounting for POSIX normalization, leading-slash stripping, and
 * hyphen-escaping mutations.
 *
 * @example Usage in a shell pipeline:
 * npm run generate:graph | npx tsx scripts/keep-only-mermaid.ts | mmdc -i - -o graph.svg
 */
import { createInterface } from 'node:readline';
import { stdin, stdout, cwd } from 'node:process';

// Configuration: Supported Mermaid start tags
const DIAGRAM_KEYWORDS = ['graph', 'flowchart', 'classDiagram', 'stateDiagram', 'erDiagram'];

// Dynamically grab the project root to strip absolute paths.
// It's not a node.js normalization but a POSIX one, in order to satisfy many
// code analysis tools (including typescript-graph, Vite, and TypeScript itself)
const rootDir = cwd().replace(/\\/g, '/');

// Account for tsg stripping the leading slash
const rootDirNoSlash = rootDir.startsWith('/') ? rootDir.substring(1) : rootDir;

// Account for tsg replacing hyphens with double-slashes in Mermaid IDs
const rootDirSanitized = rootDir.replace(/-/g, '//');
const rootDirSanitizedNoSlash = rootDirNoSlash.replace(/-/g, '//');

// Order matters: Remove longest specific strings first
const pathsToRemove = [
  rootDirSanitized + '/',
  rootDirSanitized,
  rootDirSanitizedNoSlash + '/',
  rootDirSanitizedNoSlash,
  rootDir + '/',
  rootDir,
  rootDirNoSlash + '/',
  rootDirNoSlash
];

// class labels are not displayed by some reader as Gnome viewer
// even with the configuration below.
const config = `---
config:
    htmlLabels: false
    flowchart:
        htmlLabels: false
---
`;

stdout.write(config);

const rl = createInterface({
  input: stdin,
  terminal: false
});

let foundDiagram = false;

rl.on('line', (line: string) => {
  // Strip the absolute root path from the string to force relative paths
  // let cleanLine = line.replace(new RegExp(rootDir + '/', 'g'), '');
  let cleanLine = line;
  // cleanLine = cleanLine.replace(new RegExp(rootDir, 'g'), '');
  // Use split().join() instead of Regex to avoid issues with dots in folder names
  for (const prefix of pathsToRemove) {
    cleanLine = cleanLine.split(prefix).join('');
  }

  // Early exit: If we already found the diagram, just pipe the line and skip the checks
  if (foundDiagram) {
    stdout.write(cleanLine + '\n');
    return;
  }

  // Look for the start of the diagram
  const trimmed = cleanLine.trim();
  if (DIAGRAM_KEYWORDS.some((kw) => trimmed.startsWith(kw))) {
    foundDiagram = true;
    stdout.write(cleanLine + '\n');
  }
});

rl.on('error', (err) => {
  console.error('💥 Stream Error in keep-only-mermaid:', err);
});
